package com.artvsart.config;

import org.junit.jupiter.api.Test;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertThrows;

class H2QuestionTypeConstraintMigrationTest {

    @Test
    void removesOnlyTheLegacyQuestionTypeCheck() {
        JdbcTemplate jdbcTemplate = new JdbcTemplate(
                new DriverManagerDataSource(
                        "jdbc:h2:mem:question-type-migration;DB_CLOSE_DELAY=-1",
                        "sa",
                        ""
                )
        );

        jdbcTemplate.execute("""
                CREATE TABLE artwork_questions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    question_type VARCHAR(40) NOT NULL CHECK (
                        question_type IN ('OLDER_ARTWORK')
                    ),
                    round_number INTEGER NOT NULL CHECK (round_number > 0)
                )
                """);

        new H2QuestionTypeConstraintMigration(
                jdbcTemplate
        ).migrate();

        assertDoesNotThrow(() -> jdbcTemplate.update(
                """
                INSERT INTO artwork_questions (
                    question_type,
                    round_number
                ) VALUES (?, ?)
                """,
                "ARTIST_LAST_NAME",
                1
        ));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> jdbcTemplate.update(
                        """
                        INSERT INTO artwork_questions (
                            question_type,
                            round_number
                        ) VALUES (?, ?)
                        """,
                        "ARTWORK_TITLE_WORD",
                        0
                )
        );
    }
}
