spring.application.name=Art vs Art

spring.datasource.url=jdbc:h2:file:./data/artvsart
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

artvsart.import.met.enabled=false
artvsart.import.met.target-size=200

artvsart.game.artwork-source=met