package com.artvsart.model;

public enum QuestionType {
    OLDER_ARTWORK,
    ARTIST_BORN_EARLIER,
    ARTIST_LIVED_LONGER,
    ARTIST_YOUNGER_AT_CREATION,
    ARTIST_NATIONALITY,
    ARTWORK_CULTURE,
    ARTWORK_MEDIUM,
    ARTWORK_SUBJECT,
    LARGER_ARTWORK,
    BEFORE_HISTORICAL_EVENT
}